SELECT ?example WHERE {
    ?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim .
    ?dim a qb:DimensionProperty;
    FILTER NOT EXISTS { ?obs ?dim [] }
    BIND(?dim AS ?example)
} LIMIT 1
