PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX pmd-qb: <http://publishmydata.com/def/qb/>

SELECT (?codelist as ?example) {
  <{{dataset-uri}}> qb:structure/qb:component ?component .

  ?component qb:dimension ?dimension;
    pmd-qb:codesUsed ?codelist .

  FILTER NOT EXISTS {
    ?codelist skos:member ?code .
  }
} LIMIT 1