PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdmx-concept: <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>

SELECT (?unit as ?example) {
  {
    ?unit a sdmx-concept:unitMeasure .
  } UNION {
    ?obs sdmx-attribute:unitMeasure ?unit .
  }
  
  FILTER NOT EXISTS {
    ?unit rdfs:label ?label .
  }
} LIMIT 1